import { z } from 'zod';

export const generateRequestSchema = z.object({
    format: z.string().min(1, 'フォーマットは必須です'),
    formats: z.array(z.string().min(1)).max(8).optional(),
    objective: z.string().min(1, '広告の目的は必須です'),
    brandKitId: z.string().max(100, 'ブランドキットIDが不正です').optional(),
    projectId: z.string().max(100, 'プロジェクトIDが不正です').optional(),
    sourceGenerationId: z.string().max(100, '派生元IDが不正です').optional(),
    originType: z.string().max(50, '作成種別が不正です').optional(),
    variantCount: z.number().int().min(1).max(4).optional(),
    variantMode: z.enum(['message', 'tone', 'layout']).optional(),
    productName: z.string().max(100, '長すぎます').optional(),
    campaignName: z.string().max(100, '長すぎます').optional(),
    eventName: z.string().max(100, '長すぎます').optional(),
    jobTitle: z.string().max(100, '長すぎます').optional(),
    brandName: z.string().max(100, '長すぎます').optional(),
    appName: z.string().max(100, '長すぎます').optional(),
    materialName: z.string().max(100, '長すぎます').optional(),
    storeName: z.string().max(100, '長すぎます').optional(),
    price: z.string().max(100, '価格が長すぎます').optional(),
    catchCopy: z.string().max(200, 'キャッチコピーが長すぎます').optional(),
    description: z.string().max(1000, '商品説明が長すぎます').optional(),
    targetAudience: z.string().max(100, 'ターゲット指定が長すぎます').optional(),
    discountInfo: z.string().max(200, '割引内容が長すぎます').optional(),
    campaignPeriod: z.string().max(200, '期間が長すぎます').optional(),
    campaignTargets: z.string().max(1000, '対象商品・備考が長すぎます').optional(),
    eventDateTime: z.string().max(200, '開催日時が長すぎます').optional(),
    eventLocation: z.string().max(300, '開催場所が長すぎます').optional(),
    eventContent: z.string().max(1000, 'イベント内容が長すぎます').optional(),
    companyName: z.string().max(200, '会社名が長すぎます').optional(),
    jobBenefits: z.string().max(1000, '福利厚生・アピールポイントが長すぎます').optional(),
    jobRequirements: z.string().max(1000, '必須スキル・求める人物像が長すぎます').optional(),
    brandMessage: z.string().max(300, 'ブランドメッセージが長すぎます').optional(),
    brandCoreValue: z.string().max(1000, 'コアバリューが長すぎます').optional(),
    appFeatures: z.string().max(1000, 'アプリ機能が長すぎます').optional(),
    appTargetUser: z.string().max(200, '想定ユーザーが長すぎます').optional(),
    appDownloadBenefit: z.string().max(300, 'ダウンロード特典が長すぎます').optional(),
    materialBenefits: z.string().max(1000, '資料メリットが長すぎます').optional(),
    leadCallToAction: z.string().max(300, '行動喚起が長すぎます').optional(),
    storeLocation: z.string().max(300, '店舗場所が長すぎます').optional(),
    signatureMenu: z.string().max(300, '看板メニューが長すぎます').optional(),
    specialOffer: z.string().max(300, '来店特典が長すぎます').optional(),
    customInstructions: z.string().max(16000, 'カスタム指示が長すぎます').optional(),
    tone: z.string().min(1).default('modern'),
    primaryColor: z.string().default('auto'),
    secondaryColor: z.string().default('auto'),
    autoColor: z.boolean().optional(),
    referenceImage: z.string()
        .refine((val) => !val || val.startsWith('data:image/'), { message: '不正な画像データです' })
        .optional(),
}).passthrough();

export const editRequestSchema = z.object({
    imageData: z.string().refine((val) => val.startsWith('data:image/'), { message: '不正な画像データ形式です' }),
    instruction: z.string().min(1, '編集指示は必須です').max(1000, '指示が長すぎます'),
    editType: z.string().optional(),
    thoughtSignature: z.string().optional(),
    projectId: z.string().max(100).optional(),
    brandKitId: z.string().max(100).optional(),
    sourceGenerationId: z.string().max(100).optional(),
    originType: z.string().max(50).optional(),
    format: z.unknown().optional(),
    content: z.unknown().optional(),
    branding: z.unknown().optional(),
});
