// ========================================
// 広告テンプレート定義
// ========================================


export interface AdTemplate {
    objective?: string;

    id: string;
    name: string;
    description: string;
    category: TemplateCategory;
    thumbnail: string; // グラデーションCSS or 画像URL
    icon: string;
    format: string; // adFormatsのid
    isPremium: boolean; // trueの場合は有料プランのみ利用可能
    presets: {
        tone: string;
        primaryColor: string;
        secondaryColor: string;
        catchCopy: string;
        description: string;
        targetAudience: string;
    };
    tags: string[];
    popular?: boolean;
    isNew?: boolean;
}

export type TemplateCategory =
    | 'ec'
    | 'food'
    | 'lifestyle'
    | 'tech'
    | 'fashion'
    | 'beauty'
    | 'fitness'
    | 'education'
    | 'travel'
    | 'business';

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string; icon: string }[] = [
    { id: 'ec', label: 'ECサイト', icon: '🛒' },
    { id: 'food', label: 'フード・飲料', icon: '🍽️' },
    { id: 'lifestyle', label: 'ライフスタイル', icon: '🏠' },
    { id: 'tech', label: 'テクノロジー', icon: '💻' },
    { id: 'fashion', label: 'ファッション', icon: '👗' },
    { id: 'beauty', label: 'ビューティー', icon: '💄' },
    { id: 'fitness', label: 'フィットネス', icon: '💪' },
    { id: 'education', label: '教育', icon: '📚' },
    { id: 'travel', label: '旅行', icon: '✈️' },
    { id: 'business', label: 'ビジネス', icon: '💼' },
];

export const AD_TEMPLATES: AdTemplate[] = [
    // ─── ECサイト ───
    {
        id: 'ec-flash-sale',
        objective: 'sale-campaign',
        name: 'タイムセール',
        description: '在庫限りで終了となります。お見逃しなく！',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=800&auto=format&fit=crop',
        icon: '⚡',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'bold',
            primaryColor: '#FF416C',
            secondaryColor: '#FF4B2B',
            catchCopy: '全品最大50%OFF',
            description: '今だけの特別価格でお得にゲット。見逃すな！',
            targetAudience: 'お得な買い物を求めるオンラインショッピングユーザー',
        },
        tags: ['セール', '期間限定', 'EC'],
        popular: true,
    },
    {
        id: 'ec-new-arrival',
        objective: 'new-product',
        name: '新商品発売',
        description: '最新トレンドを取り入れたコレクション。',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?q=80&w=800&auto=format&fit=crop',
        icon: '🆕',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#667eea',
            secondaryColor: '#764ba2',
            catchCopy: '待望の新作、ついに登場',
            description: '全く新しい体験を。最新コレクションをチェックしよう。',
            targetAudience: 'トレンドに敏感な20〜30代',
        },
        tags: ['新商品', 'ローンチ', 'EC'],
    },
    {
        id: 'ec-review-highlight',
        objective: 'brand-awareness',
        name: 'レビュー訴求',
        description: '1万人以上に選ばれた、確かな品質と信頼。',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
        icon: '⭐',
        format: 'facebook-ad',
        isPremium: true,
        presets: {
            tone: 'minimal',
            primaryColor: '#11998e',
            secondaryColor: '#38ef7d',
            catchCopy: 'お客様のリアルな声',
            description: '10,000人以上に選ばれた理由がここにあります。',
            targetAudience: '品質重視で口コミを参考にする消費者',
        },
        tags: ['レビュー', '口コミ', 'EC'],
    },
    {
        id: 'ec-bundle-deal',
        objective: 'sale-campaign',
        name: 'セット販売',
        description: '人気商品をセットにした限定パック。',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1556742393-d75f468bfcb0?q=80&w=800&auto=format&fit=crop',
        icon: '🎁',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#f7971e',
            secondaryColor: '#ffd200',
            catchCopy: 'まとめ買いで30%OFF',
            description: '人気商品をセットにした限定パック。単品より断然お得。',
            targetAudience: 'まとめ買いや家族用アイテムを探している消費者',
        },
        tags: ['セット販売', 'まとめ買い', 'お得', 'EC'],
        isNew: true,
    },
    {
        id: 'ec-premium-product',
        objective: 'new-product',
        name: 'プレミアム商品',
        description: '職人が丹念に仕上げたプレミアムコレクション。',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=800&auto=format&fit=crop',
        icon: '💎',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'luxury',
            primaryColor: '#1a1a2e',
            secondaryColor: '#C9A84C',
            catchCopy: '本物だけが持つ、圧倒的な質感',
            description: '職人が一点一点仕上げた、こだわりのプレミアムコレクション。',
            targetAudience: '品質にこだわる30〜50代の富裕層',
        },
        tags: ['プレミアム', '高品質', 'ラグジュアリー', 'EC'],
    },

    // ─── フード・飲料 ───
    {
        id: 'food-menu-promo',
        objective: 'new-product',
        name: '新メニュー告知',
        description: '厳選素材で仕上げた自慢の一品。',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
        icon: '🍔',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'pop',
            primaryColor: '#f5af19',
            secondaryColor: '#f12711',
            catchCopy: '新メニュー登場！',
            description: '厳選素材で仕上げた、自慢の一品をぜひお試しください。',
            targetAudience: 'グルメに興味がある20〜40代',
        },
        tags: ['フード', '新メニュー', 'レストラン'],
        popular: true,
    },
    {
        id: 'food-delivery',
        objective: 'store-visit',
        name: 'デリバリー',
        description: 'アプリからのご注文ですぐにお届け！',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?q=80&w=800&auto=format&fit=crop',
        icon: '🛵',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#00b09b',
            secondaryColor: '#96c93d',
            catchCopy: '初回注文15%OFF＆送料無料',
            description: 'お家にいながら、お店の味を楽しめます。初回注文15%OFF！',
            targetAudience: '忙しいビジネスパーソンや子育て世代',
        },
        tags: ['デリバリー', 'フード', 'クーポン'],
    },
    {
        id: 'food-cafe',
        objective: 'store-visit',
        name: 'カフェ・コーヒー',
        description: '静かな時間と、最高の一杯をお届けします。',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
        icon: '☕',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'minimal',
            primaryColor: '#6F4E37',
            secondaryColor: '#C4A882',
            catchCopy: 'ランチタイムはドリンク無料',
            description: '厳選されたシングルオリジンコーヒーを、最高の一杯で。静かな時間を、あなたと。',
            targetAudience: 'コーヒー好きな20〜40代のビジネスパーソン・学生',
        },
        tags: ['カフェ', 'コーヒー', 'ドリンク'],
    },
    {
        id: 'food-healthy',
        objective: 'brand-awareness',
        name: 'ヘルシー・オーガニック',
        description: '農薬不使用。体の中からきれいになる食事を。',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=800&auto=format&fit=crop',
        icon: '🥗',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'natural',
            primaryColor: '#56ab2f',
            secondaryColor: '#a8e063',
            catchCopy: '体が喜ぶ、自然のおいしさ',
            description: '農薬不使用のオーガニック素材だけを使用。体の中からきれいになる食事を。',
            targetAudience: '健康や美容に関心の高い20〜40代女性',
        },
        tags: ['ヘルシー', 'オーガニック', '健康食'],
        isNew: true,
    },

    // ─── テクノロジー ───
    {
        id: 'tech-saas-launch',
        objective: 'new-product',
        name: 'SaaSプロダクト',
        description: 'チームの生産性を最大200%向上させます。',
        category: 'tech',
        thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
        icon: '🚀',
        format: 'twitter-post',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#2C5364',
            secondaryColor: '#0F2027',
            catchCopy: 'ワークフローを次のレベルへ',
            description: 'クラウドベースの次世代ツールで生産性を最大200%向上。',
            targetAudience: 'スタートアップ創業者やプロダクトマネージャー',
        },
        tags: ['SaaS', 'テック', 'B2B'],
        popular: true,
    },
    {
        id: 'tech-app-download',
        objective: 'app-install',
        name: 'アプリダウンロード',
        description: '毎日の習慣を変えるスマートな機能が満載。',
        category: 'tech',
        thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop',
        icon: '📲',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#4facfe',
            secondaryColor: '#00f2fe',
            catchCopy: '無料ダウンロード！今すぐ始めよう',
            description: '累計100万ダウンロード突破。App Store & Google Playで配信中。',
            targetAudience: 'スマートフォンユーザー全般',
        },
        tags: ['アプリ', 'ダウンロード', 'モバイル'],
    },
    {
        id: 'tech-ai-product',
        objective: 'new-product',
        name: 'AIプロダクト',
        description: '最先端技術で繰り返し作業を自動化。',
        category: 'tech',
        thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?q=80&w=800&auto=format&fit=crop',
        icon: '🤖',
        format: 'twitter-post',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#6366f1',
            secondaryColor: '#8b5cf6',
            catchCopy: 'AIがあなたの仕事を10倍速くする',
            description: '最先端のAI技術で繰り返し作業を自動化。チームの生産性を劇的に改善します。',
            targetAudience: 'DX推進担当者・エンジニア・スタートアップ',
        },
        tags: ['AI', 'テクノロジー', '自動化', 'DX'],
        isNew: true,
    },

    // ─── ファッション ───
    {
        id: 'fashion-seasonal',
        objective: 'new-product',
        name: 'シーズンコレクション',
        description: 'この季節だけの特別なスタイルを提案します。',
        category: 'fashion',
        thumbnail: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop',
        icon: '👗',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'luxury',
            primaryColor: '#c471f5',
            secondaryColor: '#fa71cd',
            catchCopy: 'NEW SEASON COLLECTION',
            description: '最新トレンドを纏う。この季節だけの特別なスタイルを提案します。',
            targetAudience: 'ファッションに関心の高い20〜30代女性',
        },
        tags: ['ファッション', 'コレクション', 'シーズン'],
        popular: true,
    },
    {
        id: 'fashion-sale',
        objective: 'sale-campaign',
        name: 'ファッションセール',
        description: 'マストバイアイテムが驚きの価格に。',
        category: 'fashion',
        thumbnail: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=800&auto=format&fit=crop',
        icon: '🏷️',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'bold',
            primaryColor: '#000000',
            secondaryColor: '#D4AF37',
            catchCopy: 'FINAL SALE！最大70%OFF',
            description: '人気アイテムが驚きの価格に。お見逃しなく。',
            targetAudience: 'お得にブランドアイテムを購入したい消費者',
        },
        tags: ['セール', 'ファッション', 'EC'],
    },
    {
        id: 'fashion-streetwear',
        objective: 'brand-awareness',
        name: 'ストリートウェア',
        description: '型にはまらない、自分だけのスタイルを。',
        category: 'fashion',
        thumbnail: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?q=80&w=800&auto=format&fit=crop',
        icon: '🧢',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#1a1a1a',
            secondaryColor: '#e63946',
            catchCopy: 'BE BOLD. BE YOURSELF.',
            description: '型にはまるな。自分だけのスタイルを貫け。新コレクション、今すぐチェック。',
            targetAudience: 'カルチャーに敏感な15〜25代のZ世代',
        },
        tags: ['ストリート', 'ファッション', 'ブランド', 'Z世代'],
        isNew: true,
    },

    // ─── ビューティー ───
    {
        id: 'beauty-skincare',
        objective: 'new-product',
        name: 'スキンケア',
        description: '敏感肌にもやさしい処方で本来の美しさを。',
        category: 'beauty',
        thumbnail: 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop',
        icon: '✨',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'minimal',
            primaryColor: '#fbc2eb',
            secondaryColor: '#a6c1ee',
            catchCopy: '潤い満ちる新感覚スキンケア',
            description: '天然由来成分95%配合。敏感肌にもやさしい処方のスキンケアシリーズ。',
            targetAudience: '美容に関心の高い20〜40代女性',
        },
        tags: ['スキンケア', 'ビューティー', 'コスメ'],
    },
    {
        id: 'beauty-makeup',
        objective: 'new-product',
        name: 'メイクアップ',
        description: '個性を最大限に引き出す新コスメライン。',
        category: 'beauty',
        thumbnail: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?q=80&w=800&auto=format&fit=crop',
        icon: '💄',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#e91e63',
            secondaryColor: '#9c27b0',
            catchCopy: 'あなたらしい色で、世界を魅了しよう',
            description: '140色以上のカラーバリエーション。あなたの個性を最大限に引き出す新コスメライン。',
            targetAudience: 'メイクアップに情熱を持つ15〜35代女性',
        },
        tags: ['メイク', 'コスメ', 'ビューティー'],
        popular: true,
    },
    {
        id: 'beauty-salon',
        objective: 'store-visit',
        name: '美容サロン',
        description: '最高の技術で、あなたをもっと美しく。',
        category: 'beauty',
        thumbnail: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format&fit=crop',
        icon: '💇',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'elegant',
            primaryColor: '#d4a574',
            secondaryColor: '#3d2b1f',
            catchCopy: '全メニュー20%OFF',
            description: 'こだわりの施術と居心地のよい空間。ご予約はDMまたはWEBから。初回カット20%OFF。',
            targetAudience: '美容・自己投資に積極的な20〜40代',
        },
        tags: ['美容院', 'サロン', 'エステ'],
    },

    // ─── フィットネス ───
    {
        id: 'fitness-gym',
        objective: 'store-visit',
        name: 'ジム入会キャンペーン',
        description: 'プロトレーナーが目標達成を徹底サポート。',
        category: 'fitness',
        thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
        icon: '🏋️',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'bold',
            primaryColor: '#f7971e',
            secondaryColor: '#ffd200',
            catchCopy: '入会金無料＆初月月会費0円',
            description: '入会金無料キャンペーン実施中！ プロトレーナーがあなたの目標達成をサポート。',
            targetAudience: '健康志向の20〜40代',
        },
        tags: ['フィットネス', 'ジム', 'キャンペーン'],
    },
    {
        id: 'fitness-yoga',
        objective: 'store-visit',
        name: 'ヨガ・ピラティス',
        description: '体を整え、心を解放する時間を。',
        category: 'fitness',
        thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
        icon: '🧘',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'natural',
            primaryColor: '#667eea',
            secondaryColor: '#f5a623',
            catchCopy: '無料体験レッスン開催中',
            description: '初心者から上級者まで。あなたのペースで始められるヨガクラス。無料体験レッスン開催中。',
            targetAudience: 'ストレス解消・柔軟性向上を望む30〜50代',
        },
        tags: ['ヨガ', 'ピラティス', 'ウェルネス'],
    },
    {
        id: 'fitness-supplement',
        objective: 'new-product',
        name: 'サプリメント・プロテイン',
        description: '高品質プロテインでパフォーマンスを最大化。',
        category: 'fitness',
        thumbnail: 'https://images.unsplash.com/photo-1584466977773-e625c37cdd50?q=80&w=800&auto=format&fit=crop',
        icon: '💊',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#11998e',
            secondaryColor: '#38ef7d',
            catchCopy: '理想のボディへの最短ルート',
            description: 'トップアスリートも愛用。高品質プロテイン&栄養素でパフォーマンスを最大化。',
            targetAudience: 'アクティブに身体づくりをしている20〜35代男性',
        },
        tags: ['サプリ', 'プロテイン', 'フィットネス', '健康'],
        isNew: true,
    },

    // ─── 教育 ───
    {
        id: 'education-online-course',
        objective: 'lead-generation',
        name: 'オンラインコース',
        description: 'プロの講師による実践的なカリキュラム。',
        category: 'education',
        thumbnail: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=800&auto=format&fit=crop',
        icon: '📖',
        format: 'facebook-ad',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#5f72bd',
            secondaryColor: '#9b23ea',
            catchCopy: '【無料公開中】特別講義',
            description: 'プロの講師による実践的なカリキュラム。いつでもどこでも学べるオンラインスクール。',
            targetAudience: 'スキルアップを目指す社会人や学生',
        },
        tags: ['教育', 'オンライン学習', 'スクール'],
    },
    {
        id: 'education-language',
        objective: 'lead-generation',
        name: '語学・英会話',
        description: 'ネイティブ講師とマンツーマンで学ぶ英会話。',
        category: 'education',
        thumbnail: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=800&auto=format&fit=crop',
        icon: '🌐',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'friendly',
            primaryColor: '#4facfe',
            secondaryColor: '#00f2fe',
            catchCopy: '英語が話せると、世界が変わる',
            description: 'ネイティブ講師とマンツーマンで学ぶオンライン英会話。初回レッスン無料。今すぐ始めよう！',
            targetAudience: '英語力向上を目指す10〜40代',
        },
        tags: ['英会話', '語学', '英語', '教育'],
    },
    {
        id: 'education-programming',
        objective: 'lead-generation',
        name: 'プログラミングスクール',
        description: '確実にスキルを身につけるための学習ステップ。',
        category: 'education',
        thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
        icon: '💻',
        format: 'facebook-ad',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#0f3460',
            secondaryColor: '#e94560',
            catchCopy: 'エンジニア転職ロードマップ',
            description: '転職成功率93%。3,000人以上の転職を支援した実績あるプログラミングスクール。',
            targetAudience: '異業種からIT転職を目指す20〜35代',
        },
        tags: ['プログラミング', '転職', 'エンジニア', '教育'],
        isNew: true,
    },

    // ─── 旅行 ───
    {
        id: 'travel-resort',
        objective: 'brand-awareness',
        name: 'リゾート',
        description: '日常を忘れさせる極上のリゾート体験を。',
        category: 'travel',
        thumbnail: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=800&auto=format&fit=crop',
        icon: '🏝️',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'luxury',
            primaryColor: '#00c6fb',
            secondaryColor: '#005bea',
            catchCopy: '特別な場所で、特別な時間を',
            description: '見たことのない青い海が待っている。今シーズンのベストリゾートをご紹介。',
            targetAudience: '旅行好きな20〜50代',
        },
        tags: ['旅行', 'リゾート', 'バカンス'],
    },
    {
        id: 'travel-domestic',
        objective: 'sale-campaign',
        name: '国内旅行・観光',
        description: '絶景と心温まるおもてなし。非日常の癒しを。',
        category: 'travel',
        thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=800&auto=format&fit=crop',
        icon: '🗾',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'warm',
            primaryColor: '#f45b69',
            secondaryColor: '#ee9b00',
            catchCopy: '【秋の旅行応援】最大30%OFF',
            description: '四季折々の絶景と、心温まるおもてなし。憧れの旅先があなたを待っています。',
            targetAudience: '国内旅行を楽しむ30〜60代',
        },
        tags: ['国内旅行', '観光', '日本', '旅'],
    },

    // ─── ビジネス ───
    {
        id: 'business-seminar',
        objective: 'event-seminar',
        name: 'セミナー・ウェビナー',
        description: 'マーケティングの最先端を学べる90分。',
        category: 'business',
        thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&auto=format&fit=crop',
        icon: '🎤',
        format: 'facebook-ad',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#1a2a6c',
            secondaryColor: '#fdbb2d',
            catchCopy: '業界のトップが語る最新戦略',
            description: '限定100名。マーケティングの最先端を今すぐキャッチアップ。',
            targetAudience: '経営者・マーケティング担当者',
        },
        tags: ['セミナー', 'ウェビナー', 'B2B'],
    },
    {
        id: 'business-recruitment',
        objective: 'recruitment',
        name: '採用・求人',
        description: '新しい価値を創造し、共に成長できる仲間を。',
        category: 'business',
        thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=800&auto=format&fit=crop',
        icon: '🤝',
        format: 'facebook-ad',
        isPremium: true,
        presets: {
            tone: 'trustworthy',
            primaryColor: '#0072b1',
            secondaryColor: '#00a0dc',
            catchCopy: 'フルリモート・年間休日125日',
            description: 'チャレンジを楽しめる人を求めています。フルフレックス・フルリモート対応。カジュアル面談から。',
            targetAudience: '転職・就活中のエンジニア・デザイナー・マーケター',
        },
        tags: ['採用', '求人', '人材', '転職'],
    },
    {
        id: 'business-consulting',
        objective: 'lead-generation',
        name: 'コンサルティング',
        description: 'ビジネス課題を可視化するチェックリスト。',
        category: 'business',
        thumbnail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=800&auto=format&fit=crop',
        icon: '📊',
        format: 'google-display',
        isPremium: true,
        presets: {
            tone: 'professional',
            primaryColor: '#1a3a5c',
            secondaryColor: '#2d6a9f',
            catchCopy: '【無料診断シート】課題を最速で解決へ',
            description: '業界トップクラスのコンサルタントが、あなたのビジネス課題に向き合います。初回相談無料。',
            targetAudience: '経営課題を抱える中小企業の経営者・役員',
        },
        tags: ['コンサル', 'B2B', 'ビジネス', '課題解決'],
        isNew: true,
    },

    // ─── ライフスタイル ───
    {
        id: 'lifestyle-subscription',
        objective: 'lead-generation',
        name: 'サブスクリプション',
        description: 'プロが厳選したアイテムが毎月届きます。',
        category: 'lifestyle',
        thumbnail: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?q=80&w=800&auto=format&fit=crop',
        icon: '📦',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'cute',
            primaryColor: '#f093fb',
            secondaryColor: '#f5576c',
            catchCopy: '毎月届くワクワク体験',
            description: 'プロが厳選したアイテムが毎月届く、新しいライフスタイル体験。初月50%OFF。',
            targetAudience: 'サブスクリプションサービスに興味がある20〜30代',
        },
        tags: ['サブスク', 'ライフスタイル', '定期購入'],
    },
    {
        id: 'lifestyle-interior',
        objective: 'new-product',
        name: 'インテリア・家具',
        description: 'シンプルで機能的な、理想の空間を。',
        category: 'lifestyle',
        thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800&auto=format&fit=crop',
        icon: '🛋️',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'minimal',
            primaryColor: '#d4a574',
            secondaryColor: '#f5efe6',
            catchCopy: '暮らしに、上質なリズムを',
            description: '北欧デザインにインスパイアされた家具コレクション。シンプルで機能的な、理想の空間を。',
            targetAudience: '住空間にこだわるライフスタイル志向の30〜50代',
        },
        tags: ['インテリア', '家具', 'ライフスタイル', '北欧'],
        isNew: true,
    },
    {
        id: 'lifestyle-pet',
        objective: 'new-product',
        name: 'ペット用品',
        description: '獣医師監修のプレミアムペットフード。',
        category: 'lifestyle',
        thumbnail: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=800&auto=format&fit=crop',
        icon: '🐾',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'warm',
            primaryColor: '#ff6b6b',
            secondaryColor: '#feca57',
            catchCopy: '大切な家族に、最高のものを',
            description: '獣医師監修のプレミアムペットフード。愛するペットの健康と幸せのために。',
            targetAudience: 'ペットを家族として大切にしている飼い主世代',
        },
        tags: ['ペット', '動物', 'ライフスタイル'],
    },
];
