// ========================================
// 広告テンプレート定義
// ========================================


export interface AdTemplate {
    id: string;
    name: string;
    description: string;
    category: TemplateCategory;
    thumbnail: string; // グラデーションCSS or 画像URL
    icon: string;
    format: string; // adFormatsのid
    isPremium: boolean; // trueの場合は有料プランのみ利用可能
    presets: {
        tone: string;
        primaryColor: string;
        secondaryColor: string;
        catchCopy: string;
        description: string;
        targetAudience: string;
    };
    tags: string[];
    popular?: boolean;
    isNew?: boolean;
}

export type TemplateCategory =
    | 'ec'
    | 'food'
    | 'lifestyle'
    | 'tech'
    | 'fashion'
    | 'beauty'
    | 'fitness'
    | 'education'
    | 'travel'
    | 'business';

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string; icon: string }[] = [
    { id: 'ec', label: 'ECサイト', icon: '🛒' },
    { id: 'food', label: 'フード・飲料', icon: '🍽️' },
    { id: 'lifestyle', label: 'ライフスタイル', icon: '🏠' },
    { id: 'tech', label: 'テクノロジー', icon: '💻' },
    { id: 'fashion', label: 'ファッション', icon: '👗' },
    { id: 'beauty', label: 'ビューティー', icon: '💄' },
    { id: 'fitness', label: 'フィットネス', icon: '💪' },
    { id: 'education', label: '教育', icon: '📚' },
    { id: 'travel', label: '旅行', icon: '✈️' },
    { id: 'business', label: 'ビジネス', icon: '💼' },
];

export const AD_TEMPLATES: AdTemplate[] = [
    // ─── ECサイト ───
    {
        id: 'ec-flash-sale',
        name: 'タイムセール',
        description: '期間限定セールの緊急感を演出する広告テンプレート',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=800&auto=format&fit=crop',
        icon: '⚡',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'bold',
            primaryColor: '#FF416C',
            secondaryColor: '#FF4B2B',
            catchCopy: '【期間限定】タイムセール開催中！',
            description: '今だけの特別価格でお得にゲット。見逃すな！',
            targetAudience: 'お得な買い物を求めるオンラインショッピングユーザー',
        },
        tags: ['セール', '期間限定', 'EC'],
        popular: true,
    },
    {
        id: 'ec-new-arrival',
        name: '新商品発売',
        description: '新商品のローンチを華やかに告知するテンプレート',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?q=80&w=800&auto=format&fit=crop',
        icon: '🆕',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#667eea',
            secondaryColor: '#764ba2',
            catchCopy: '「NEW ARRIVAL」ついに登場！',
            description: '全く新しい体験を。最新コレクションをチェックしよう。',
            targetAudience: 'トレンドに敏感な20〜30代',
        },
        tags: ['新商品', 'ローンチ', 'EC'],
    },
    {
        id: 'ec-review-highlight',
        name: 'レビュー訴求',
        description: 'お客様の声を活用した信頼性の高い広告テンプレート',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
        icon: '⭐',
        format: 'facebook-ad',
        isPremium: true,
        presets: {
            tone: 'minimal',
            primaryColor: '#11998e',
            secondaryColor: '#38ef7d',
            catchCopy: '★4.8の高評価！ お客様のリアルな声',
            description: '10,000人以上に選ばれた理由がここにあります。',
            targetAudience: '品質重視で口コミを参考にする消費者',
        },
        tags: ['レビュー', '口コミ', 'EC'],
    },
    {
        id: 'ec-bundle-deal',
        name: 'セット販売',
        description: 'まとめ買い・バンドル商品のお得感を際立たせるテンプレート',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1556742393-d75f468bfcb0?q=80&w=800&auto=format&fit=crop',
        icon: '🎁',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#f7971e',
            secondaryColor: '#ffd200',
            catchCopy: '3点まとめ買いで30%OFF！ お得なセットを今だけ',
            description: '人気商品をセットにした限定パック。単品より断然お得。',
            targetAudience: 'まとめ買いや家族用アイテムを探している消費者',
        },
        tags: ['セット販売', 'まとめ買い', 'お得', 'EC'],
        isNew: true,
    },
    {
        id: 'ec-premium-product',
        name: 'プレミアム商品',
        description: '高価格帯・高品質商品の価値を洗練されたビジュアルで表現',
        category: 'ec',
        thumbnail: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=800&auto=format&fit=crop',
        icon: '💎',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'luxury',
            primaryColor: '#1a1a2e',
            secondaryColor: '#C9A84C',
            catchCopy: '本物だけが持つ、圧倒的な質感。',
            description: '職人が一点一点仕上げた、こだわりのプレミアムコレクション。',
            targetAudience: '品質にこだわる30〜50代の富裕層',
        },
        tags: ['プレミアム', '高品質', 'ラグジュアリー', 'EC'],
    },

    // ─── フード・飲料 ───
    {
        id: 'food-menu-promo',
        name: '新メニュー告知',
        description: '新メニューを美味しそうに紹介するテンプレート',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop',
        icon: '🍔',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'pop',
            primaryColor: '#f5af19',
            secondaryColor: '#f12711',
            catchCopy: '新メニュー登場！ この美味しさ、体験して',
            description: '厳選素材で仕上げた、自慢の一品をぜひお試しください。',
            targetAudience: 'グルメに興味がある20〜40代',
        },
        tags: ['フード', '新メニュー', 'レストラン'],
        popular: true,
    },
    {
        id: 'food-delivery',
        name: 'デリバリー',
        description: 'デリバリーサービスの利便性を訴求するテンプレート',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?q=80&w=800&auto=format&fit=crop',
        icon: '🛵',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#00b09b',
            secondaryColor: '#96c93d',
            catchCopy: '今すぐ注文、すぐにお届け！',
            description: 'お家にいながら、お店の味を楽しめます。初回注文15%OFF！',
            targetAudience: '忙しいビジネスパーソンや子育て世代',
        },
        tags: ['デリバリー', 'フード', 'クーポン'],
    },
    {
        id: 'food-cafe',
        name: 'カフェ・コーヒー',
        description: 'カフェの雰囲気やドリンクの魅力を伝えるテンプレート',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
        icon: '☕',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'minimal',
            primaryColor: '#6F4E37',
            secondaryColor: '#C4A882',
            catchCopy: 'ひと口で、世界が変わる。',
            description: '厳選されたシングルオリジンコーヒーを、最高の一杯で。静かな時間を、あなたと。',
            targetAudience: 'コーヒー好きな20〜40代のビジネスパーソン・学生',
        },
        tags: ['カフェ', 'コーヒー', 'ドリンク'],
    },
    {
        id: 'food-healthy',
        name: 'ヘルシー・オーガニック',
        description: '健康志向のフード・ドリンクブランドに最適なテンプレート',
        category: 'food',
        thumbnail: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=800&auto=format&fit=crop',
        icon: '🥗',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'natural',
            primaryColor: '#56ab2f',
            secondaryColor: '#a8e063',
            catchCopy: '体が喜ぶ、自然のおいしさ。',
            description: '農薬不使用のオーガニック素材だけを使用。体の中からきれいになる食事を。',
            targetAudience: '健康や美容に関心の高い20〜40代女性',
        },
        tags: ['ヘルシー', 'オーガニック', '健康食'],
        isNew: true,
    },

    // ─── テクノロジー ───
    {
        id: 'tech-saas-launch',
        name: 'SaaSプロダクト',
        description: 'テック系プロダクトの洗練されたプロモーション',
        category: 'tech',
        thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
        icon: '🚀',
        format: 'twitter-post',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#2C5364',
            secondaryColor: '#0F2027',
            catchCopy: '業務を革新する。あなたのワークフローを次のレベルへ',
            description: 'クラウドベースの次世代ツールで生産性を最大200%向上。',
            targetAudience: 'スタートアップ創業者やプロダクトマネージャー',
        },
        tags: ['SaaS', 'テック', 'B2B'],
        popular: true,
    },
    {
        id: 'tech-app-download',
        name: 'アプリダウンロード',
        description: 'モバイルアプリのDL促進テンプレート',
        category: 'tech',
        thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop',
        icon: '📲',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#4facfe',
            secondaryColor: '#00f2fe',
            catchCopy: '無料ダウンロード！ 今すぐはじめよう',
            description: '累計100万ダウンロード突破。App Store & Google Playで配信中。',
            targetAudience: 'スマートフォンユーザー全般',
        },
        tags: ['アプリ', 'ダウンロード', 'モバイル'],
    },
    {
        id: 'tech-ai-product',
        name: 'AIプロダクト',
        description: 'AI・機械学習製品の先進性と信頼感を伝えるテンプレート',
        category: 'tech',
        thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?q=80&w=800&auto=format&fit=crop',
        icon: '🤖',
        format: 'twitter-post',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#6366f1',
            secondaryColor: '#8b5cf6',
            catchCopy: 'AIが、あなたの仕事を10倍速くする。',
            description: '最先端のAI技術で繰り返し作業を自動化。チームの生産性を劇的に改善します。',
            targetAudience: 'DX推進担当者・エンジニア・スタートアップ',
        },
        tags: ['AI', 'テクノロジー', '自動化', 'DX'],
        isNew: true,
    },

    // ─── ファッション ───
    {
        id: 'fashion-seasonal',
        name: 'シーズンコレクション',
        description: '季節の新作コレクションを美しく演出するテンプレート',
        category: 'fashion',
        thumbnail: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop',
        icon: '👗',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'luxury',
            primaryColor: '#c471f5',
            secondaryColor: '#fa71cd',
            catchCopy: 'NEW SEASON COLLECTION',
            description: '最新トレンドを纏う。この季節だけの特別なスタイルを提案します。',
            targetAudience: 'ファッションに関心の高い20〜30代女性',
        },
        tags: ['ファッション', 'コレクション', 'シーズン'],
        popular: true,
    },
    {
        id: 'fashion-sale',
        name: 'ファッションセール',
        description: '最大70%OFFなどの大型セールを訴求するテンプレート',
        category: 'fashion',
        thumbnail: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=800&auto=format&fit=crop',
        icon: '🏷️',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'bold',
            primaryColor: '#000000',
            secondaryColor: '#D4AF37',
            catchCopy: 'FINAL SALE ─ 最大70%OFF',
            description: '人気アイテムが驚きの価格に。お見逃しなく。',
            targetAudience: 'お得にブランドアイテムを購入したい消費者',
        },
        tags: ['セール', 'ファッション', 'EC'],
    },
    {
        id: 'fashion-streetwear',
        name: 'ストリートウェア',
        description: 'ストリートカルチャーを体現したエッジの効いたブランド広告',
        category: 'fashion',
        thumbnail: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?q=80&w=800&auto=format&fit=crop',
        icon: '🧢',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#1a1a1a',
            secondaryColor: '#e63946',
            catchCopy: 'BE BOLD. BE YOURSELF.',
            description: '型にはまるな。自分だけのスタイルを貫け。新コレクション、今すぐチェック。',
            targetAudience: 'カルチャーに敏感な15〜25代のZ世代',
        },
        tags: ['ストリート', 'ファッション', 'ブランド', 'Z世代'],
        isNew: true,
    },

    // ─── ビューティー ───
    {
        id: 'beauty-skincare',
        name: 'スキンケア',
        description: '清潔感のあるスキンケア商品のプロモーション',
        category: 'beauty',
        thumbnail: 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop',
        icon: '✨',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'minimal',
            primaryColor: '#fbc2eb',
            secondaryColor: '#a6c1ee',
            catchCopy: '素肌に自信を。',
            description: '天然由来成分95%配合。敏感肌にもやさしい処方のスキンケアシリーズ。',
            targetAudience: '美容に関心の高い20〜40代女性',
        },
        tags: ['スキンケア', 'ビューティー', 'コスメ'],
    },
    {
        id: 'beauty-makeup',
        name: 'メイクアップ',
        description: '鮮やかな発色と個性的なデザインで惹きつけるコスメ広告',
        category: 'beauty',
        thumbnail: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?q=80&w=800&auto=format&fit=crop',
        icon: '💄',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#e91e63',
            secondaryColor: '#9c27b0',
            catchCopy: 'あなたらしい色で、世界を染めよう。',
            description: '140色以上のカラーバリエーション。あなたの個性を最大限に引き出す新コスメライン。',
            targetAudience: 'メイクアップに情熱を持つ15〜35代女性',
        },
        tags: ['メイク', 'コスメ', 'ビューティー'],
        popular: true,
    },
    {
        id: 'beauty-salon',
        name: '美容サロン',
        description: '美容室・エステサロンの雰囲気と技術をアピールするテンプレート',
        category: 'beauty',
        thumbnail: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format&fit=crop',
        icon: '💇',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'elegant',
            primaryColor: '#d4a574',
            secondaryColor: '#3d2b1f',
            catchCopy: '最高の技術で、あなたをもっと美しく。',
            description: 'こだわりの施術と居心地のよい空間。ご予約はDMまたはWEBから。初回カット20%OFF。',
            targetAudience: '美容・自己投資に積極的な20〜40代',
        },
        tags: ['美容院', 'サロン', 'エステ'],
    },

    // ─── フィットネス ───
    {
        id: 'fitness-gym',
        name: 'ジム入会キャンペーン',
        description: 'パワフルでモチベーションを高めるジム広告',
        category: 'fitness',
        thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
        icon: '🏋️',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'bold',
            primaryColor: '#f7971e',
            secondaryColor: '#ffd200',
            catchCopy: '今日から変わる。新しい自分に会いに行こう',
            description: '入会金無料キャンペーン実施中！ プロトレーナーがあなたの目標達成をサポート。',
            targetAudience: '健康志向の20〜40代',
        },
        tags: ['フィットネス', 'ジム', 'キャンペーン'],
    },
    {
        id: 'fitness-yoga',
        name: 'ヨガ・ピラティス',
        description: '心身の調和と穏やかさを表現するヨガ・ピラティスのテンプレート',
        category: 'fitness',
        thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
        icon: '🧘',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'natural',
            primaryColor: '#667eea',
            secondaryColor: '#f5a623',
            catchCopy: '体を整え、心を解放する。',
            description: '初心者から上級者まで。あなたのペースで始められるヨガクラス。無料体験レッスン開催中。',
            targetAudience: 'ストレス解消・柔軟性向上を望む30〜50代',
        },
        tags: ['ヨガ', 'ピラティス', 'ウェルネス'],
    },
    {
        id: 'fitness-supplement',
        name: 'サプリメント・プロテイン',
        description: '健康補助食品・プロテインの効果と信頼性を訴求するテンプレート',
        category: 'fitness',
        thumbnail: 'https://images.unsplash.com/photo-1584466977773-e625c37cdd50?q=80&w=800&auto=format&fit=crop',
        icon: '💊',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'bold',
            primaryColor: '#11998e',
            secondaryColor: '#38ef7d',
            catchCopy: '科学が証明した、理想のボディへの最短ルート。',
            description: 'トップアスリートも愛用。高品質プロテイン&栄養素でパフォーマンスを最大化。',
            targetAudience: 'アクティブに身体づくりをしている20〜35代男性',
        },
        tags: ['サプリ', 'プロテイン', 'フィットネス', '健康'],
        isNew: true,
    },

    // ─── 教育 ───
    {
        id: 'education-online-course',
        name: 'オンラインコース',
        description: 'オンライン学習サービスの受講者募集テンプレート',
        category: 'education',
        thumbnail: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=80&w=800&auto=format&fit=crop',
        icon: '📖',
        format: 'facebook-ad',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#5f72bd',
            secondaryColor: '#9b23ea',
            catchCopy: '今日から始める、未来への投資',
            description: 'プロの講師による実践的なカリキュラム。いつでもどこでも学べるオンラインスクール。',
            targetAudience: 'スキルアップを目指す社会人や学生',
        },
        tags: ['教育', 'オンライン学習', 'スクール'],
    },
    {
        id: 'education-language',
        name: '語学・英会話',
        description: '英語・外国語学習サービスのキャッチーなプロモーション',
        category: 'education',
        thumbnail: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=800&auto=format&fit=crop',
        icon: '🌐',
        format: 'instagram-story',
        isPremium: false,
        presets: {
            tone: 'friendly',
            primaryColor: '#4facfe',
            secondaryColor: '#00f2fe',
            catchCopy: '英語が話せると、世界が変わる。',
            description: 'ネイティブ講師とマンツーマンで学ぶオンライン英会話。初回レッスン無料。今すぐ始めよう！',
            targetAudience: '英語力向上を目指す10〜40代',
        },
        tags: ['英会話', '語学', '英語', '教育'],
    },
    {
        id: 'education-programming',
        name: 'プログラミングスクール',
        description: 'エンジニア転職・プログラミング学習を促す力強いテンプレート',
        category: 'education',
        thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
        icon: '💻',
        format: 'facebook-ad',
        isPremium: true,
        presets: {
            tone: 'modern',
            primaryColor: '#0f3460',
            secondaryColor: '#e94560',
            catchCopy: '未経験から6ヶ月でエンジニア転職を実現。',
            description: '転職成功率93%。3,000人以上の転職を支援した実績あるプログラミングスクール。',
            targetAudience: '異業種からIT転職を目指す20〜35代',
        },
        tags: ['プログラミング', '転職', 'エンジニア', '教育'],
        isNew: true,
    },

    // ─── 旅行 ───
    {
        id: 'travel-resort',
        name: 'リゾート',
        description: '夢のような旅先を訴求する旅行広告テンプレート',
        category: 'travel',
        thumbnail: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=800&auto=format&fit=crop',
        icon: '🏝️',
        format: 'instagram-story',
        isPremium: true,
        presets: {
            tone: 'luxury',
            primaryColor: '#00c6fb',
            secondaryColor: '#005bea',
            catchCopy: '特別な場所で、特別な時間を。',
            description: '見たことのない青い海が待っている。今シーズンのベストリゾートをご紹介。',
            targetAudience: '旅行好きな20〜50代',
        },
        tags: ['旅行', 'リゾート', 'バカンス'],
    },
    {
        id: 'travel-domestic',
        name: '国内旅行・観光',
        description: '国内旅行・観光地の魅力を地域の雰囲気とともに伝えるテンプレート',
        category: 'travel',
        thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=800&auto=format&fit=crop',
        icon: '🗾',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'warm',
            primaryColor: '#f45b69',
            secondaryColor: '#ee9b00',
            catchCopy: '日本の美しさ、再発見。',
            description: '四季折々の絶景と、心温まるおもてなし。憧れの旅先があなたを待っています。',
            targetAudience: '国内旅行を楽しむ30〜60代',
        },
        tags: ['国内旅行', '観光', '日本', '旅'],
    },

    // ─── ビジネス ───
    {
        id: 'business-seminar',
        name: 'セミナー・ウェビナー',
        description: 'ビジネスセミナーの集客用テンプレート',
        category: 'business',
        thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&auto=format&fit=crop',
        icon: '🎤',
        format: 'facebook-ad',
        isPremium: false,
        presets: {
            tone: 'modern',
            primaryColor: '#1a2a6c',
            secondaryColor: '#fdbb2d',
            catchCopy: '無料ウェビナー開催！ 業界のトップが語る最新戦略',
            description: '限定100名。マーケティングの最先端を今すぐキャッチアップ。',
            targetAudience: '経営者・マーケティング担当者',
        },
        tags: ['セミナー', 'ウェビナー', 'B2B'],
    },
    {
        id: 'business-recruitment',
        name: '採用・求人',
        description: '求職者に響く、企業ブランドを前面に出した採用広告',
        category: 'business',
        thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=800&auto=format&fit=crop',
        icon: '🤝',
        format: 'facebook-ad',
        isPremium: true,
        presets: {
            tone: 'trustworthy',
            primaryColor: '#0072b1',
            secondaryColor: '#00a0dc',
            catchCopy: '一緒に、世界を変えよう。仲間を募集中。',
            description: 'チャレンジを楽しめる人を求めています。フルフレックス・フルリモート対応。カジュアル面談から。',
            targetAudience: '転職・就活中のエンジニア・デザイナー・マーケター',
        },
        tags: ['採用', '求人', '人材', '転職'],
    },
    {
        id: 'business-consulting',
        name: 'コンサルティング',
        description: '課題解決力とプロフェッショナリズムを伝えるB2Bサービス広告',
        category: 'business',
        thumbnail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=800&auto=format&fit=crop',
        icon: '📊',
        format: 'google-display',
        isPremium: true,
        presets: {
            tone: 'professional',
            primaryColor: '#1a3a5c',
            secondaryColor: '#2d6a9f',
            catchCopy: '課題の本質を捉え、最速で解決へ。',
            description: '業界トップクラスのコンサルタントが、あなたのビジネス課題に向き合います。初回相談無料。',
            targetAudience: '経営課題を抱える中小企業の経営者・役員',
        },
        tags: ['コンサル', 'B2B', 'ビジネス', '課題解決'],
        isNew: true,
    },

    // ─── ライフスタイル ───
    {
        id: 'lifestyle-subscription',
        name: 'サブスクリプション',
        description: '定期購入サービスの魅力を伝えるテンプレート',
        category: 'lifestyle',
        thumbnail: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?q=80&w=800&auto=format&fit=crop',
        icon: '📦',
        format: 'instagram-feed',
        isPremium: false,
        presets: {
            tone: 'cute',
            primaryColor: '#f093fb',
            secondaryColor: '#f5576c',
            catchCopy: '毎月届くワクワク。あなただけのキュレーション',
            description: 'プロが厳選したアイテムが毎月届く、新しいライフスタイル体験。初月50%OFF。',
            targetAudience: 'サブスクリプションサービスに興味がある20〜30代',
        },
        tags: ['サブスク', 'ライフスタイル', '定期購入'],
    },
    {
        id: 'lifestyle-interior',
        name: 'インテリア・家具',
        description: '上質な空間づくりを提案するインテリアブランドのテンプレート',
        category: 'lifestyle',
        thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800&auto=format&fit=crop',
        icon: '🛋️',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'minimal',
            primaryColor: '#d4a574',
            secondaryColor: '#f5efe6',
            catchCopy: '暮らしに、上質なリズムを。',
            description: '北欧デザインにインスパイアされた家具コレクション。シンプルで機能的な、理想の空間を。',
            targetAudience: '住空間にこだわるライフスタイル志向の30〜50代',
        },
        tags: ['インテリア', '家具', 'ライフスタイル', '北欧'],
        isNew: true,
    },
    {
        id: 'lifestyle-pet',
        name: 'ペット用品',
        description: 'ペットと飼い主の絆を大切にするペット用品ブランドのテンプレート',
        category: 'lifestyle',
        thumbnail: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=800&auto=format&fit=crop',
        icon: '🐾',
        format: 'instagram-feed',
        isPremium: true,
        presets: {
            tone: 'warm',
            primaryColor: '#ff6b6b',
            secondaryColor: '#feca57',
            catchCopy: '大切な家族に、最高のものを。',
            description: '獣医師監修のプレミアムペットフード。愛するペットの健康と幸せのために。',
            targetAudience: 'ペットを家族として大切にしている飼い主世代',
        },
        tags: ['ペット', '動物', 'ライフスタイル'],
    },
];
